version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dingtalk-agent-client
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/resource:/app/static/resource
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dingtalk-network

networks:
  dingtalk-network:
    driver: bridge