version: '3.8'

services:
  app:
    build: .
    container_name: dingtalk-agent-client
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/resource:/app/static/resource
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - dingtalk-network

networks:
  dingtalk-network:
    driver: bridge